### ISSUE TITLE
[Next.js] Error: Should provide a fetch function under Node.js

### ISSUE THREAD

**Issue by jacksonrakena** [logto-io/js#327]
Firstly, I'd like to say that Logto sounds like a great project. Excited for what could become of this.  
  
When running a Next.js app with the `logto-io/react` connector, I get this issue before I can even load the page:
![image](https://user-images.githubusercontent.com/44521335/178142977-ea8791cc-bd89-4764-a6ae-f2e9e1740092.png)
My LogtoProvider setup is fairly standard:
```ts
<LogtoProvider
        config={{
          endpoint: "https://id-v2-dev.animalswithcoolhats.com",
          appId: "u50kz2fnWde4KcxD1QdBM",
        }}
      >
```  
  
I suspect it's something to do with SSR, the page being rendered on the server is tripping some kind of error inside a dependency.

**Comment by gao-sun** [comment]
@wangsijie @demonzoo let's fix this

**Comment by demonzoo** [comment]
First and foremost, thank you for your support! @jacksonrakena 

And let me explain this error a little bit, starting with our JS SDK infrastructure.
In our current design, we have `@logto/js` (we also call it js core SDK), which is a so-called "platform agnostic" SDK and can be used in both browser and node.js server environment.
And on top of the js core SDK, we built `@logto/browser`, which is the foundation of all web-ish SDKs.
Then on top of the browser SDK, we built `@logto/react` and `@logto/vue`, which can only be used in react and vue projects.

Their relationship is kinda as follows:

```
js core
  |---browser
           |---react
           |---vue
  |---node.js ( <-- your use case)
```

And let's get back to your issue. From the code sample above, it looks like you are using the `@logto/react` sdk, which is built on top of `@logto/browser` sdk and expected to be run in a browser environment.
The error, is thrown from the js core (requester.ts) when logto tries to create a request to OIDC server, and that request is made by a `fetch` function, which is by default provided in the `global` context in browser environment, but not available in node.js environment (at least not in node 16).
  
So if you want to use logto with next.js at this moment, you can't use `@logto/react` SDK, because that's in the browser SDK family. And due to the fact that we don't have a `@logto/node` SDK at the moment, you'll have to built your authentication functions from the js core level. You can refer to the [traditional web integration guide](https://docs.logto.io/docs/recipes/integrate-logto/traditional) documentation, which consists of an node.js sample project using express and jade.

The ultimate solution, however, is building a `@logto/node` SDK and even a `@logto/next` SDK on top of it, in which a node.js fetch solution is provided out of the box (e.g. using `node-fetch`). I can promise you that this would be supported officially in the near future. Just stay tuned!

**Comment by gao-sun** [comment]
@demonzoo is there a possibility to simply provide a "fetch" function in Node.js in order to finish the server side rendering? looks like the OP is in the React context, but executed under Node.js.

**Comment by demonzoo** [comment]
The OP is "in the React context" because he's using Next.js, which is basically just React on the server side.
Another option is to allow user to specify `fetch` function implementation in the `LogtoConfig`. So that even in browser env, if the user doesn't want to use the browser default `fetch`, he can choose something else.
But LogtoConfig is defined in browser SDK, and this seems really unnecessary in the browser SDK family.

**Comment by gao-sun** [comment]
@jacksonrakena we're still investigating the best practice of Next.js, and the conclusion may change since we're not finalized yet.

You may continue or hold the exploration until we have something solid. We just don't want to mislead you to the wrong direction. Cheers.

**Comment by wangsijie** [comment]
We have Next.js SDK now 🎉 check [sample](https://github.com/logto-io/js/tree/master/packages/next-sample) for more details.

**Comment by gao-sun** [comment]
@jacksonrakena you try it and close the issue if it works

**Comment by gao-sun** [comment]
@jacksonrakena feel free to reach us again if it doesn't work. cheers!

**Comment by hanrea** [comment]
Adding a comment can solve compilation errors on the node platform : 
```typescript
 // @ts-expect-error fetch is not recognised as a valid global.
export const createRequester = (fetchFunction: typeof fetch): Requester => {
  .......
}
```
https://github.com/logto-io/js/blob/4f23bf9c2693bd2420c9df22345ef44bd00907a0/packages/client/src/utils/requester.ts#L4
