### ISSUE TITLE
feature request: example showing using a refresh token

### ISSUE THREAD

**Issue by kalebscholes** [logto-io/js#504]
### What problem did you meet?
I'm building out an application and everything works great until the JWT expires, I can see a refresh token stored in the local storage but not sure the best way to access it and use it to get a new token.

### Describe what you'd like Logto to have
I'd love an example (I'm currently working with Vue) on how to use the refresh token

**Comment by wangsijie** [comment]
Are you using the official SDK? It will handle this by calling "getAccessToken": if the local access token is expired, will try to grant new access token using the local refresh token.

**Comment by kalebscholes** [comment]
Oh perfect, I guess I didn't realize it was also handling that. I am using the official Vue SDK but I've been running into issues getting it to work inside of an axios interceptor with the Vue warning `inject() can only be used inside setup() or functional components` and an error from the package stating `Error parsing authorization code Error: Must install Logto plugin first` so I've been attempting to work around that.

**Comment by wangsijie** [comment]
@charIeszhao can you take a look at this vue issue when convenient?

**Comment by charIeszhao** [comment]
> Oh perfect, I guess I didn't realize it was also handling that. I am using the official Vue SDK but I've been running into issues getting it to work inside of an axios interceptor with the Vue warning `inject() can only be used inside setup() or functional components` and an error from the package stating `Error parsing authorization code Error: Must install Logto plugin first` so I've been attempting to work around that.

First of all, `@logto/vue` only supports Vue 3 since it's heavily dependent on `composables`, so if are using Vue 2 then it will not work whatsoever.

And the second error can be resolved by injecting logto plugin first in your root file (typically a `main.ts` file), e.g.:
```ts
import { createApp } from "vue";
import App from "./App.vue";
import { createLogto } from "@logto/vue";

const app = createApp(App);

app.use(createLogto, {
  appId: <your-app-id>
  endpoint: <your-endpoint-url>
});
...
```

As for the axios interceptor error, since you are not sharing the code, I can only guess you are using `useLogto` and its `getAccessToken` method in a non-composable js/ts file? But since `useLogto` is a composable, it can only be called in a function component's `setup()` script OR another composable. So in your case I would recommend wrapping your axios interceptor code in a Vue 3 composable first before calling `getAccessToken()`.

**Comment by charIeszhao** [comment]
Closing the ticket due to inactivity. Feel free to reopen if there's anything unclear. Thanks
