### ISSUE TITLE
How to refresh IdToken?

### ISSUE THREAD

**Issue by isaced** [logto-io/js#846]
At present, I obtain the IdToken through `{ getIdToken } = useLogto();`(react) and then pass it to the back-end structure for authentication through the HTTP Authorization Header.

At the beginning, it works well. However, the JWT expires after one hour and will not be refreshed.

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Modify the useLogto hook to automatically refresh the IdToken when it's close to expiration. This will ensure that the IdToken remains valid for authentication with the back-end.

I also created pull request: https://github.com/logto-io/js/pull/847


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by darcyYe** [comment]
Would you like to provide more details on how you gonna use ID token in your project?
Usually you should rely on `access token` for authorization. In Logto, we only use the existence of `idToken` to check whether a user is authenticated. And ID token is refreshed along with the refresh of any access token. So far, we do not provide an API to actively refresh ID token.

**Comment by darcyYe** [comment]
> After integrating my application with Logto, I use the `idToken` to protect the backend APIs. Since I only need simple user authentication without requiring fine-grained control over API authorization, I opted to use the idToken.
> 
> I didn't create an api-resource in the Logto console but instead used the idToken directly for authentication. In my backend's `jwtVerify` call, I did not use the `audience` parameter.

You should always use an access token to protect API resources, even if you don't need fine-grained access control.
